### ISSUE TITLE
Error: ebay API request failed [500]

### ISSUE THREAD

**Issue by dcaud** [gsimchoni/ebayr#2]
After `search_ebay("elvis costume")` I'm receiving this error. This comes after I set  `EbayToken("a_token_generated_by_ebay")` by the text string generated after I go to developer.ebay.com -> Production -> User Tokens -> Auth'n'Auth -> Sign into Production.

It is a text string with approx. 800 characters. Is that the correct token?

(I also tried a AppID/ClientID that was appox. 40 characters and that gave the same error message)

**Comment by dcaud** [comment]
Resolved the issue by removing all variables from my session...I guess something odd was being stored in the environment.

**Comment by bkcarson** [comment]
I am also getting the following error: `Error: ebay API request failed [500]`. I received my token via developer.ebay.com -> Production -> User Tokens -> Auth'n'Auth -> Sign into Production and I tried removing all variables from my session and clearing my workspace. Has the ebayr package been deprecated?

**Comment by gsimchoni** [comment]
Hi @bkcarson, as said in the README, this package no longer works, ebay changed their API long ago. Sorry.
